{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gregtechceu.gtceu",
    "module": "gtm-reborn-1.20.1",
    "version": "8.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2.jar",
          "url": "gtm-reborn-1.20.1-8.3.2.jar",
          "size": 19702448,
          "sha512": "c8b5120d33dc96914f04fc4e6dd76a5375434dfe7ce1709f6c7500ccdb7e0a5245e339739ed55e2c0f02829643227af960a520a194f38fc54c2f1b861b0a494d",
          "sha256": "5055953a6a21a7ab984bdc74750d33b9f3000ae882e0339b8db1e014ddeea23e",
          "sha1": "f77469c30062b94205cfed73f768039766ba06bf",
          "md5": "3063459b880dddb9258cda7d27c90f17"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2.jar",
          "url": "gtm-reborn-1.20.1-8.3.2.jar",
          "size": 19702448,
          "sha512": "c8b5120d33dc96914f04fc4e6dd76a5375434dfe7ce1709f6c7500ccdb7e0a5245e339739ed55e2c0f02829643227af960a520a194f38fc54c2f1b861b0a494d",
          "sha256": "5055953a6a21a7ab984bdc74750d33b9f3000ae882e0339b8db1e014ddeea23e",
          "sha1": "f77469c30062b94205cfed73f768039766ba06bf",
          "md5": "3063459b880dddb9258cda7d27c90f17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2-sources.jar",
          "url": "gtm-reborn-1.20.1-8.3.2-sources.jar",
          "size": 10851337,
          "sha512": "95b229ac365e517694a09160a1d2911dbc4556932ed5b382b3871d2176e540c0e2dd47ee670f867dbb5163b44c8436da29b44a3ff9af818500be5033d1a04cbf",
          "sha256": "55e0c09d85af09111d5e210f6cbf303acdd555addb2d900707107e4755a34b47",
          "sha1": "a843debeeb1802507d3b13bbbf84212cb571006f",
          "md5": "2c5831cf8c56a88d64947b8d2b5f1438"
        }
      ]
    }
  ]
}
