{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gregtechceu.gtceu",
    "module": "gtm-reborn-1.20.1",
    "version": "8.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2.jar",
          "url": "gtm-reborn-1.20.1-8.3.2.jar",
          "size": 19703823,
          "sha512": "7e91f817d0e6c1ad6db11d4f69e72d0cdf67ebc1b8e94d8db1122a63e577305558520fd78469a091948ec2e6745ab48118e907d38153f3974b13cd285fed1819",
          "sha256": "b6785b56b0c038fd156abb67bdf6fe6cfd2989ab76f3b32fdc70004b31696a6c",
          "sha1": "7696e8d62105079161ba3ec2d6b9bb346afaacdb",
          "md5": "cfa71a1566e0a440ba96b883108c570e"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2.jar",
          "url": "gtm-reborn-1.20.1-8.3.2.jar",
          "size": 19703823,
          "sha512": "7e91f817d0e6c1ad6db11d4f69e72d0cdf67ebc1b8e94d8db1122a63e577305558520fd78469a091948ec2e6745ab48118e907d38153f3974b13cd285fed1819",
          "sha256": "b6785b56b0c038fd156abb67bdf6fe6cfd2989ab76f3b32fdc70004b31696a6c",
          "sha1": "7696e8d62105079161ba3ec2d6b9bb346afaacdb",
          "md5": "cfa71a1566e0a440ba96b883108c570e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2-sources.jar",
          "url": "gtm-reborn-1.20.1-8.3.2-sources.jar",
          "size": 10852214,
          "sha512": "3f71cbb61aba0655e61107399296be244d1f9f2b20ddc69852a97bcec1eb81178ea33d3d30857c493ed26f113e4e8465de1dd19648d3a3f31fa8f9a33fb1cff9",
          "sha256": "1b11b4200981034c0bc8f04b205480cc009dcfbdcb74436509a4cfbb66449106",
          "sha1": "f3a11308076d6d898bc84859eed019a0f5dcc042",
          "md5": "e7f7ccdc56e966cfd40fd0b7d476a61c"
        }
      ]
    }
  ]
}
