{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gregtechceu.gtceu",
    "module": "gtm-reborn-1.20.1",
    "version": "8.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2.jar",
          "url": "gtm-reborn-1.20.1-8.3.2.jar",
          "size": 19702448,
          "sha512": "f0abd1ab6330314b28d4b087320868bd2d5ff123db4049cff368c40ee82bfbeb38466d21e15f094822b860a0e744948764511321ac43ab262f9356936b368100",
          "sha256": "d3225f8734c60f96abf96eedd4222c072fd975c1cd29fcaca75050f203a9564e",
          "sha1": "7cf0b0088da1479c3a5686f11b819e0b4680bdc6",
          "md5": "2abea39b4d6c8c8ad395ef8621c3b471"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2.jar",
          "url": "gtm-reborn-1.20.1-8.3.2.jar",
          "size": 19702448,
          "sha512": "f0abd1ab6330314b28d4b087320868bd2d5ff123db4049cff368c40ee82bfbeb38466d21e15f094822b860a0e744948764511321ac43ab262f9356936b368100",
          "sha256": "d3225f8734c60f96abf96eedd4222c072fd975c1cd29fcaca75050f203a9564e",
          "sha1": "7cf0b0088da1479c3a5686f11b819e0b4680bdc6",
          "md5": "2abea39b4d6c8c8ad395ef8621c3b471"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtm-reborn-1.20.1-8.3.2-sources.jar",
          "url": "gtm-reborn-1.20.1-8.3.2-sources.jar",
          "size": 10851337,
          "sha512": "f9971d5f46b820442aec0e020e6c5937566741498c5995844d603efa7f44fdeb6cdf444760921c9e6d605f888345fad3d7498bc630c8c8333ddb8ed62c18b961",
          "sha256": "c8da32730883f83e5b3b9d8d51b758b9f361fdacd5362379e512a10dbf4d6d2f",
          "sha1": "166dfd7fadf7ab1ed6bce5196dd6d05f65ec9392",
          "md5": "8fc9779c66ea05f396b4c8f3e69228e3"
        }
      ]
    }
  ]
}
