{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "2.2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1.jar",
          "url": "gtecore-1.20.1-2.2.5.1.jar",
          "size": 8230934,
          "sha512": "57da70992fda64adbfccacc37a2ca5ca93bbf8c418eecf42bdce2a9c6f1bfcff2c4b24494b14928de742ccc9e12a350c59d93ea38ff0449e4270515cb6794152",
          "sha256": "6b3094869ee25635c7cdd4e5b1f6dfcab68c20714a895c5d64be76b1d609b845",
          "sha1": "5beb6489c86a760f740e88aa82e8d950103e3949",
          "md5": "9ce72914bd37c7f2f0d7be0b9737a3db"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1.jar",
          "url": "gtecore-1.20.1-2.2.5.1.jar",
          "size": 8230934,
          "sha512": "57da70992fda64adbfccacc37a2ca5ca93bbf8c418eecf42bdce2a9c6f1bfcff2c4b24494b14928de742ccc9e12a350c59d93ea38ff0449e4270515cb6794152",
          "sha256": "6b3094869ee25635c7cdd4e5b1f6dfcab68c20714a895c5d64be76b1d609b845",
          "sha1": "5beb6489c86a760f740e88aa82e8d950103e3949",
          "md5": "9ce72914bd37c7f2f0d7be0b9737a3db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1-sources.jar",
          "url": "gtecore-1.20.1-2.2.5.1-sources.jar",
          "size": 8064728,
          "sha512": "89072846b4055ddadd9f52128f3a68a3d34800baa63011d0e809ad56f3ed48f6e361706ea41058a77d2bcadf0ff5bbf2761ad177ada37f64a8fb59f8db1dc0e7",
          "sha256": "80f66812c282e4aac50d5701583f55fbd57d577026b48253c5850721e8d059f7",
          "sha1": "91404619e15a8904f52e769d6dbbada1d0656f1e",
          "md5": "d66b30b545e9b57256380f5dc9ee9d42"
        }
      ]
    }
  ]
}
