{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "2.2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1.jar",
          "url": "gtecore-1.20.1-2.2.5.1.jar",
          "size": 8230934,
          "sha512": "924da49dc143a1c3e96672bdec48aba38a229d6de4d2ec60ab273454c2d5fff540a33bcf536caecfcb1f99142fd6d9f409679f59b514e1cde2f49381cc06de97",
          "sha256": "a4b7e9ad9a1ebf9e88916fd0d8dfde666a59d5614ec6e3e808c9505123763c34",
          "sha1": "3ddd31b34c558df0e3309cd7b164b469f7255032",
          "md5": "4fab523707e71eb3ce0b50d5c20530cc"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1.jar",
          "url": "gtecore-1.20.1-2.2.5.1.jar",
          "size": 8230934,
          "sha512": "924da49dc143a1c3e96672bdec48aba38a229d6de4d2ec60ab273454c2d5fff540a33bcf536caecfcb1f99142fd6d9f409679f59b514e1cde2f49381cc06de97",
          "sha256": "a4b7e9ad9a1ebf9e88916fd0d8dfde666a59d5614ec6e3e808c9505123763c34",
          "sha1": "3ddd31b34c558df0e3309cd7b164b469f7255032",
          "md5": "4fab523707e71eb3ce0b50d5c20530cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1-sources.jar",
          "url": "gtecore-1.20.1-2.2.5.1-sources.jar",
          "size": 8064728,
          "sha512": "dc155491bd259f229a9076a0705cb4f0016e1ec6dbcc089a0d3f22378bc4ba384e759e54f7edc258cb995533777ef7389d82fa33574d85cedd271b7583536e2c",
          "sha256": "4dc1bcff2434523f6900a42f657891155a76a16ddfe2fdce533e6cadc0a36b22",
          "sha1": "6c0990c27d12180c20c763b08731ce49afb0de18",
          "md5": "902e55c5f5687a3cbf218594418518cc"
        }
      ]
    }
  ]
}
