{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "2.2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1.jar",
          "url": "gtecore-1.20.1-2.2.5.1.jar",
          "size": 8230934,
          "sha512": "6db055845439230fc7f5af2c985f2e9ca21ba289bf03f8952a61bfd10b70d2dc3efba8bb834dfe9cdb786ab5b89e916f7133a436e681466ff1bc51bc28b0013f",
          "sha256": "7bf7b12fb967236e996d229b7a926a3032e3db9e207ea6db684a396595d3f3b9",
          "sha1": "b35c7e224853c9bb5252cf60cbd63b4e97dd51e0",
          "md5": "c2d37841a623ffa7a37cbccaf8fb4f58"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1.jar",
          "url": "gtecore-1.20.1-2.2.5.1.jar",
          "size": 8230934,
          "sha512": "6db055845439230fc7f5af2c985f2e9ca21ba289bf03f8952a61bfd10b70d2dc3efba8bb834dfe9cdb786ab5b89e916f7133a436e681466ff1bc51bc28b0013f",
          "sha256": "7bf7b12fb967236e996d229b7a926a3032e3db9e207ea6db684a396595d3f3b9",
          "sha1": "b35c7e224853c9bb5252cf60cbd63b4e97dd51e0",
          "md5": "c2d37841a623ffa7a37cbccaf8fb4f58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-2.2.5.1-sources.jar",
          "url": "gtecore-1.20.1-2.2.5.1-sources.jar",
          "size": 8064728,
          "sha512": "90d0580c764bf17653d2ebb3394eeaa6810eb308121b3677b749cf7f36f638c7d255a1b34fe3326b54b62766e254b13af4eb37bf2a6a8a6e98363b42f1d0b03e",
          "sha256": "76e3a515f369573dcf6f6ab22c1d6f9da1aa22cbd4bc61360462fd4dd97be02e",
          "sha1": "f869a6a41c406b8347e9dbee42f955876e538355",
          "md5": "895d2750daae91be2df15eefcc776424"
        }
      ]
    }
  ]
}
