{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly-ed5c094",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "size": 11230136,
          "sha512": "10459409c4a09da54ec8468ad7cdb7f1b9381839f4d98ad2bdadfd862d511d973c2fee092e46050f0c7b10284f9283fcd358347d5afb67b5507d1d25cc555b07",
          "sha256": "492e313de5a7a646350ee6449a41bff3754f748c058bd068f6a79f73a1f98098",
          "sha1": "74fea67c5c79cc4f437dd90540c665bb7675cf27",
          "md5": "f9140ad9b0235f5b8cdf6a3a5c91856c"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "size": 11230136,
          "sha512": "10459409c4a09da54ec8468ad7cdb7f1b9381839f4d98ad2bdadfd862d511d973c2fee092e46050f0c7b10284f9283fcd358347d5afb67b5507d1d25cc555b07",
          "sha256": "492e313de5a7a646350ee6449a41bff3754f748c058bd068f6a79f73a1f98098",
          "sha1": "74fea67c5c79cc4f437dd90540c665bb7675cf27",
          "md5": "f9140ad9b0235f5b8cdf6a3a5c91856c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-ed5c094-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-ed5c094-sources.jar",
          "size": 11046407,
          "sha512": "bb40e21353477898bda3e1d935a3432a74be00a242a14892e8f5f21ef66903ea243c899a6ab1c9ca291d86d7c5e22f5439d6103ffbb6897bd102e050a0d17851",
          "sha256": "25c6c45de12b57469cb90a508edc6d148a840c53a7176675b7827f275d233d6e",
          "sha1": "f9696e9b0b66ada61429399bbeec8f80c2b55cb7",
          "md5": "1c160d740d228d19fef9f999ce9e0945"
        }
      ]
    }
  ]
}
