{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly-ed5c094",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "size": 11230136,
          "sha512": "1a5859b0f0da5f6c559bf74b68d6d2dee6ca2e10872706cacbe321b6c2444ae95715e12f3859ac88961280acc018b9a04c44f793ee32df279ff4e96675da4d42",
          "sha256": "f77e888a742007b1aa33f3d09894992547d745f3973229891c117bea5a1d7361",
          "sha1": "2825d2278aa5e433d50b1255eb5a0f66957ff4cb",
          "md5": "35b66e5c0eb57d641d6da33b984bb111"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-ed5c094.jar",
          "size": 11230136,
          "sha512": "1a5859b0f0da5f6c559bf74b68d6d2dee6ca2e10872706cacbe321b6c2444ae95715e12f3859ac88961280acc018b9a04c44f793ee32df279ff4e96675da4d42",
          "sha256": "f77e888a742007b1aa33f3d09894992547d745f3973229891c117bea5a1d7361",
          "sha1": "2825d2278aa5e433d50b1255eb5a0f66957ff4cb",
          "md5": "35b66e5c0eb57d641d6da33b984bb111"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-ed5c094-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-ed5c094-sources.jar",
          "size": 11046409,
          "sha512": "f8e37d1b236d2c51ee66ffe5dabb3bcd9c7099cb5661d77e0fbb5c6621e30ce54214e6a41f38deb15e3c78ec2b69ec7777a47a548789e8310fdea20e82661dc5",
          "sha256": "9d2ea140df3bd9d53a67444282078fc15cefd4ce164ad3ad99acc926b2901ee6",
          "sha1": "65435b299c274907e7cd659dc930433e109a23bf",
          "md5": "5f37dd3aa817e199f36d2b388814db86"
        }
      ]
    }
  ]
}
