name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "129168a9fb79f4d03c6306feaa790106ee8bbecf076448da107887343f65846d"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
