name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abca4f4b527b84d5939696aabd6140eb22fa63f447627683c818b060f71f4651"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
