name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17f7e2c156a1520b3df4460c22edca70c34d2129dfeea9a3c205cef0a64bc372"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
