name = "GregTech Easy"
author = "takanashisatou"
version = "1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa6d80c36668a1b80a137f4dfa7f0e273fcf0a51c7d1bb6e03b1b869e25ee6d5"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
