name = "Gregtech-Easy"
author = "takanashisatou,qiuye"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1078ac3891ae3281751070b67691c3fa3d53614ee8b6aa285d0482daf5558aae"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
