name = "Gregtech-Easy"
author = "takanashisatou,qiuye"
version = "1.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8a23bb371a5ecbdd6c495b242017f22128b5f86b58299b60b5848bb6d01e66d"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
