name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50e3ac15d044c04cbfc6c90999a275ec8840c774fd903489593d30f7198518b5"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
