name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7403aad80d58f231ad90f4b84bc2fb58f86ba8267323d4277916a2412cef2ffe"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
