name = "Gregtech-Easy"
author = "takanashisatou,qiuye"
version = "1.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b604c778699bf9686044c1da63b184187a6f2dd4abcec19632e28bd5992aafe"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
