name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a89060bb10bc2c6ef705fa8ae79d03df161efaf6f5d6098544dabba55bbc16be"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
