name = "Gregtech-Easy"
author = "takanashisatou,qiuye"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd7883917f890c951834124272a21018489c2a1c8812de67a153b04e2ab2122c"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
