name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eecd469100ca6ac08129ac145a1fc0746ee8a2d2d5f6ef0c34e0bff524e8133"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
