name = "Gregtech Easy"
author = "takanashisatou,qiuye"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f899513bda785fb614d59884fde6f3cd94113fbbbcbd8f366a4c3a3863c62a16"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
