name = "Gregtech-Easy"
author = "takanashisatou,qiuye"
version = "1.7.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "311551a4a2cd402eefb62958085423526a28d122b7915d09719c4f6371225003"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
