{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly-4bbc415",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "size": 11242086,
          "sha512": "04c5e00a0f83df2c739bcb0a4ac9a05e3f20a0b49901d88ee96e0c8e3f6a9f03309815190dff8a79a44431a1aec1081f511b7ce51ec613a4f8368efe33381300",
          "sha256": "520b8d35139eece43e00037039c4f70b2a9666b8c28ba20b42c25cd780aca16c",
          "sha1": "603e3790da5778cabc88a5b7f86d87224ef63fa4",
          "md5": "7544c48cf4d923528402773f0fb7c58a"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "size": 11242086,
          "sha512": "04c5e00a0f83df2c739bcb0a4ac9a05e3f20a0b49901d88ee96e0c8e3f6a9f03309815190dff8a79a44431a1aec1081f511b7ce51ec613a4f8368efe33381300",
          "sha256": "520b8d35139eece43e00037039c4f70b2a9666b8c28ba20b42c25cd780aca16c",
          "sha1": "603e3790da5778cabc88a5b7f86d87224ef63fa4",
          "md5": "7544c48cf4d923528402773f0fb7c58a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-4bbc415-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-4bbc415-sources.jar",
          "size": 11054140,
          "sha512": "cf291e65d5df73670e0148c6a791645287fc6256ad8ae9dd39804c18a3cc8e0a41cdc5b7775faee510e998c501f16f55fa93cde205435e5fa3c69aa8382109bc",
          "sha256": "bbdd15ab79ba63c0de4825f6e0a75adb77cd485ffa395f5fcf396600c85aeb4e",
          "sha1": "47af129adfac27d89f24532b908454dc626b60c8",
          "md5": "c190e2eff53f142f55391e13ed231e44"
        }
      ]
    }
  ]
}
