{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly-4bbc415",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "size": 11242086,
          "sha512": "af90bd9a06c437e73fde4b8aca11bfa654ae4f5f0fed45c60289acce703dd93b87d96415bd3189ae35c05500e211f0c168bc14d2e2f6a326aa1cb6b5cea24f89",
          "sha256": "a2bf3bbac7a267381d076782308f9c65194dbc854d3ba69ecdba1cc75a5a20f3",
          "sha1": "176d7ff718104c0e212b48a786ca0a98d23bfa9b",
          "md5": "1b297cb7da86f7b0fc832d68a8fbeb0a"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-4bbc415.jar",
          "size": 11242086,
          "sha512": "af90bd9a06c437e73fde4b8aca11bfa654ae4f5f0fed45c60289acce703dd93b87d96415bd3189ae35c05500e211f0c168bc14d2e2f6a326aa1cb6b5cea24f89",
          "sha256": "a2bf3bbac7a267381d076782308f9c65194dbc854d3ba69ecdba1cc75a5a20f3",
          "sha1": "176d7ff718104c0e212b48a786ca0a98d23bfa9b",
          "md5": "1b297cb7da86f7b0fc832d68a8fbeb0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-4bbc415-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-4bbc415-sources.jar",
          "size": 11054145,
          "sha512": "f40c57147658f5d8755122f95b2ddcf011e36c77136cfdadb1c33397838112f0640f58228fd223b5fd7e1247aac269fee7bdd3b72349b58dfab09454dd53d708",
          "sha256": "18daec9543c3f0d8280479e656e0654565b9aa9706764b4e5c01050cd8f94e6e",
          "sha1": "9b08fd1ca65a0763c11265a6dfa1c19e96f931b6",
          "md5": "c04600b94b306fbe8ae7a6202d7a4289"
        }
      ]
    }
  ]
}
