{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly-07218ff",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-07218ff.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-07218ff.jar",
          "size": 11242086,
          "sha512": "8a9f19ac81fe0d0bea61dbd40a1400d469e3ae7ac07ac89952ec238f7d7928cefced0641769242ff489c77e5e4957e2b7cbf9dfd6f31c1e9737a345eb1e6ae95",
          "sha256": "abd4a93d43e129d456a942c6d2269189773b889a8a823a9b7a86ca151c08d8b5",
          "sha1": "a8ec5260b5aaa66194ebc477669e62b1f790cfaf",
          "md5": "f3356da6cc033681891c40eb882b6ea1"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-07218ff.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-07218ff.jar",
          "size": 11242086,
          "sha512": "8a9f19ac81fe0d0bea61dbd40a1400d469e3ae7ac07ac89952ec238f7d7928cefced0641769242ff489c77e5e4957e2b7cbf9dfd6f31c1e9737a345eb1e6ae95",
          "sha256": "abd4a93d43e129d456a942c6d2269189773b889a8a823a9b7a86ca151c08d8b5",
          "sha1": "a8ec5260b5aaa66194ebc477669e62b1f790cfaf",
          "md5": "f3356da6cc033681891c40eb882b6ea1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-07218ff-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-07218ff-sources.jar",
          "size": 11054145,
          "sha512": "69f7332af7e770828b6f58120886a12afca191347d699d7a517eb775bd09847ffd706c621e13a5c7c445f187c7da89f0c3c4ca642d4a78d0ca50f66ba121ddb7",
          "sha256": "1d1ac268195eee1b818bae2f20eac36cd4a6f6698170ac70c72951f7e4503c5c",
          "sha1": "5959b0016120a2ae6da35a4ee33ac5df290fb068",
          "md5": "f7803c8151afed3aa5fcc7ff0f5967c5"
        }
      ]
    }
  ]
}
