{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.5-nightly",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly.jar",
          "size": 11009402,
          "sha512": "4077a98bffe6ca31283ecd4b13a65f0a81b8dfa49abf84117cf9fd0d3d7a92e8a6567a9572bd9b2a4b186181f4ab70c9c5273ada9c1e1fdc21e33ae074944b9f",
          "sha256": "c2e9ebcede21f7784d2cb98a305c99c3e5dc92c32749c4bddfb45cb4648cee02",
          "sha1": "1c9b3e54e86891038a02186d6373f8d756605ce8",
          "md5": "2313ccab5ce4bec247c7d045395a4aa2"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly.jar",
          "size": 11009402,
          "sha512": "4077a98bffe6ca31283ecd4b13a65f0a81b8dfa49abf84117cf9fd0d3d7a92e8a6567a9572bd9b2a4b186181f4ab70c9c5273ada9c1e1fdc21e33ae074944b9f",
          "sha256": "c2e9ebcede21f7784d2cb98a305c99c3e5dc92c32749c4bddfb45cb4648cee02",
          "sha1": "1c9b3e54e86891038a02186d6373f8d756605ce8",
          "md5": "2313ccab5ce4bec247c7d045395a4aa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly-sources.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly-sources.jar",
          "size": 10776562,
          "sha512": "3e54605693da5b1b2898dd427f033bd256c73f6a6d24daeaff1ab7c633ac566d3128f0f498f221f84afc4328509e220d576473a2fbf95f2489aa4e93a8ac1692",
          "sha256": "2d4df97eb9ff15171dbb49f9e2a552875aa23772c7e84dbeac48471a289f3ae3",
          "sha1": "b30d5960391703c3a1eef45a0c8ecec270f374d7",
          "md5": "6f69105d3eafef387cdc692061b0eeef"
        }
      ]
    }
  ]
}
