{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.5-nightly",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly.jar",
          "size": 11003372,
          "sha512": "833aa4ef1980085192ca661d88037b14c61b2a128465fae85ae50b04fed4df4dcbfb098a4523bf7b663bbe353d5b9105d470245a7aba90b46b8cea33c6d44f5c",
          "sha256": "9b5a848cf46fe2565394ea318fac3c03f830369c442e6038c353878938c86e3f",
          "sha1": "50f7632d9227c84baf14d58490d64cb2820cff2c",
          "md5": "c62b62e44fe6291c03cd82d5cf0b602e"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly.jar",
          "size": 11003372,
          "sha512": "833aa4ef1980085192ca661d88037b14c61b2a128465fae85ae50b04fed4df4dcbfb098a4523bf7b663bbe353d5b9105d470245a7aba90b46b8cea33c6d44f5c",
          "sha256": "9b5a848cf46fe2565394ea318fac3c03f830369c442e6038c353878938c86e3f",
          "sha1": "50f7632d9227c84baf14d58490d64cb2820cff2c",
          "md5": "c62b62e44fe6291c03cd82d5cf0b602e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly-sources.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly-sources.jar",
          "size": 10770084,
          "sha512": "3e127a8e0c0f2607a250ac5025701c6072e4734d02bfe9b3b748f05c07fdd5d6178585c48ba267b7401f07466769535a377123d56ad6e120d5807c47b63a42c1",
          "sha256": "a5e244259a5ffd00812c66bb4b4c2f580e37adf259e3bca41f74301d9f31c601",
          "sha1": "dd5be497cc0cf349524fdc87df310f6aba4cb4ff",
          "md5": "e2b2f307754a2351f9d11c8b749d81de"
        }
      ]
    }
  ]
}
