{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.5-nightly",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly.jar",
          "size": 11006034,
          "sha512": "7fdf824e8bff1e080d2e4cb66197a9a739a8def080749d7f6dba9aca372b7da513b2de09031854abcc7462a3b1cb8e62c82105107c47b3315bc5c5103a11faf9",
          "sha256": "0da208a4c0d99aaa223dd77aadb79a7d51f3e36a5380709f9e110924f6954beb",
          "sha1": "2dd70e2d2005b63ae4832f45b3a87a34b5eeb922",
          "md5": "370cf30654a227621cc7581f8db45587"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly.jar",
          "size": 11006034,
          "sha512": "7fdf824e8bff1e080d2e4cb66197a9a739a8def080749d7f6dba9aca372b7da513b2de09031854abcc7462a3b1cb8e62c82105107c47b3315bc5c5103a11faf9",
          "sha256": "0da208a4c0d99aaa223dd77aadb79a7d51f3e36a5380709f9e110924f6954beb",
          "sha1": "2dd70e2d2005b63ae4832f45b3a87a34b5eeb922",
          "md5": "370cf30654a227621cc7581f8db45587"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.5-nightly-sources.jar",
          "url": "gtecore-1.20.1-3.0.5-nightly-sources.jar",
          "size": 10772452,
          "sha512": "9c544da1c29b054522f0ad970b0ddb42c5432d15169b37cbe45841c2fb7346b083516ba561a0f5be05463e8922c274f921fcb9bd1bf2b85346597c73c68818bb",
          "sha256": "624752efd2aa68e79c24368c34055c2e04cccc3e9c91af1efed7b1cda8641e4f",
          "sha1": "db95799bc6902484e6805c08c6c24e389b116356",
          "md5": "01f80d0402f40c6a6b4bd5c7f1a14a41"
        }
      ]
    }
  ]
}
