{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arbor",
    "module": "gt---1.20.1",
    "version": "1.3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gt---1.20.1-1.3.5.1.jar",
          "url": "gt---1.20.1-1.3.5.1.jar",
          "size": 8867750,
          "sha512": "b53841a3d3b6a0261c944ba809bf334b899ba0230c8380f81d36a926886e6abb4d07f9156ca7a2aad854761c3d61ffd1837ffef2928b083a252ce0096c496373",
          "sha256": "4bfeb6a948c9207a376fbff73eaaff94775308a5d85df7c039c8d9bb53870c6f",
          "sha1": "f7f9a5781ba86c1532cb54040432bcb1e490a8a3",
          "md5": "ca85a361a6d190cc4286fa86ea9e3c0b"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gt---1.20.1-1.3.5.1.jar",
          "url": "gt---1.20.1-1.3.5.1.jar",
          "size": 8867750,
          "sha512": "b53841a3d3b6a0261c944ba809bf334b899ba0230c8380f81d36a926886e6abb4d07f9156ca7a2aad854761c3d61ffd1837ffef2928b083a252ce0096c496373",
          "sha256": "4bfeb6a948c9207a376fbff73eaaff94775308a5d85df7c039c8d9bb53870c6f",
          "sha1": "f7f9a5781ba86c1532cb54040432bcb1e490a8a3",
          "md5": "ca85a361a6d190cc4286fa86ea9e3c0b"
        }
      ]
    }
  ]
}
