{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arbor",
    "module": "gt---1.20.1",
    "version": "1.3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gt---1.20.1-1.3.5.1.jar",
          "url": "gt---1.20.1-1.3.5.1.jar",
          "size": 8867745,
          "sha512": "d1b13bcaaa968522213818252c9477389d3fae684a139d47320829c84ffe91e06cc5f93cd0df34f0862a7b095578d77c4479a65845337b2a41cefd7b9828544b",
          "sha256": "873b2f87a7546fd024e15bc8a8985445a66b3e7e320203066b33acdaf26df8b1",
          "sha1": "332514d80f72343a7e7fb024c4eeabf2480ebf2e",
          "md5": "248256c34efaf5e7446fd6838d63365d"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gt---1.20.1-1.3.5.1.jar",
          "url": "gt---1.20.1-1.3.5.1.jar",
          "size": 8867745,
          "sha512": "d1b13bcaaa968522213818252c9477389d3fae684a139d47320829c84ffe91e06cc5f93cd0df34f0862a7b095578d77c4479a65845337b2a41cefd7b9828544b",
          "sha256": "873b2f87a7546fd024e15bc8a8985445a66b3e7e320203066b33acdaf26df8b1",
          "sha1": "332514d80f72343a7e7fb024c4eeabf2480ebf2e",
          "md5": "248256c34efaf5e7446fd6838d63365d"
        }
      ]
    }
  ]
}
