{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arbor",
    "module": "gt---1.20.1",
    "version": "1.3.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gt---1.20.1-1.3.5.1.jar",
          "url": "gt---1.20.1-1.3.5.1.jar",
          "size": 8867745,
          "sha512": "20585b6d80c8d7595b7d29d8b0f431bfad548585c66f00c90bd2f94c7189d7f9b28456ebe9450fa24bd4107fac708ec4c08f39d3edd81a46b636b4c861c54bff",
          "sha256": "77c3f9ca0e84c90e2fe75739a4b8757e8135aac2f988e1bbaf2cc562ae0f25d5",
          "sha1": "36955a485852c23b1835a69ddb1c9f9969022128",
          "md5": "617b42ccd1248c33278dd6ca8668e451"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gt---1.20.1-1.3.5.1.jar",
          "url": "gt---1.20.1-1.3.5.1.jar",
          "size": 8867745,
          "sha512": "20585b6d80c8d7595b7d29d8b0f431bfad548585c66f00c90bd2f94c7189d7f9b28456ebe9450fa24bd4107fac708ec4c08f39d3edd81a46b636b4c861c54bff",
          "sha256": "77c3f9ca0e84c90e2fe75739a4b8757e8135aac2f988e1bbaf2cc562ae0f25d5",
          "sha1": "36955a485852c23b1835a69ddb1c9f9969022128",
          "md5": "617b42ccd1248c33278dd6ca8668e451"
        }
      ]
    }
  ]
}
