
[extendedae_plus]
	#扩展样板供应器总槽位容量的倍率。
	#基础为36，每页仍显示36格，倍率会增加总页数/总容量。
	#建议范围 1-16
	#Range: 1 ~ 64
	pageMultiplier = 1
	#无线收发器最大连接距离（单位：方块）
	#从端与主端的直线距离需小于等于该值才会建立连接。
	#Range: 1.0 ~ 4096.0
	wirelessMaxRange = 256.0
	#是否允许无线收发器跨维度建立连接
	#开启后，从端可连接到不同维度的主端（忽略距离限制）
	wirelessCrossDimEnable = true

