{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly-b5f306e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-b5f306e.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-b5f306e.jar",
          "size": 11245897,
          "sha512": "8dde823bad60a512a652cbc87859e57a7eeb5408152bfbf00f36c969b72d148818ad8a45b59e085e56e552ac7660bd970802189201708ac72d96dfe5f1578b8e",
          "sha256": "b59db0b6c5159aee90af49cc815c64ab95f807157745a39fb0e9b78d9e4ac97e",
          "sha1": "73c1742719dcd8e171f063a3e973d422a0a2c3be",
          "md5": "4e3b583535bbf3067ecd73db3826bf4d"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-b5f306e.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-b5f306e.jar",
          "size": 11245897,
          "sha512": "8dde823bad60a512a652cbc87859e57a7eeb5408152bfbf00f36c969b72d148818ad8a45b59e085e56e552ac7660bd970802189201708ac72d96dfe5f1578b8e",
          "sha256": "b59db0b6c5159aee90af49cc815c64ab95f807157745a39fb0e9b78d9e4ac97e",
          "sha1": "73c1742719dcd8e171f063a3e973d422a0a2c3be",
          "md5": "4e3b583535bbf3067ecd73db3826bf4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-b5f306e-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-b5f306e-sources.jar",
          "size": 11059254,
          "sha512": "413082958d26fa8dcf60772c2f4143e0b007543fcf5c4f6a914ab16f87b01a5515fce81393b464dc0c305d2630678dcce3fa5c42250935046b3889d598f321ba",
          "sha256": "4d0622a83331a3d8fda57010c60272f49729658221cf7fc66dc95fc3bf1a67fc",
          "sha1": "53f8d5fad389eb1c6c5fece4f5b63afbb54664d6",
          "md5": "d370bea56bbd042170979e94accec9a9"
        }
      ]
    }
  ]
}
