{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly.jar",
          "size": 11014913,
          "sha512": "fe90edbe62c66f24982a30aab187a1237b7ca9b040513563eae385f730ffa7d6e230f1f32e2ca7dc89c01a862c98b0dc8d460759e954b674c66e6dc514cead42",
          "sha256": "a8c19d2910d24d9a376b1de1143415d5aed0ae20e2d30c60365e680acdd6cbaf",
          "sha1": "d88bc5434fd28242641b7ed65821f09f30628329",
          "md5": "faf63dec25f56cbef278591f2c331823"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly.jar",
          "size": 11014913,
          "sha512": "fe90edbe62c66f24982a30aab187a1237b7ca9b040513563eae385f730ffa7d6e230f1f32e2ca7dc89c01a862c98b0dc8d460759e954b674c66e6dc514cead42",
          "sha256": "a8c19d2910d24d9a376b1de1143415d5aed0ae20e2d30c60365e680acdd6cbaf",
          "sha1": "d88bc5434fd28242641b7ed65821f09f30628329",
          "md5": "faf63dec25f56cbef278591f2c331823"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-sources.jar",
          "size": 10779315,
          "sha512": "9d5bf2302e6412dfcb86b9ed430255b8c3c29d4bc20eb96de2d9767047fba1a0595f515103970c21886752a6728970fee78e85d9842690ca485437feb3c0a60d",
          "sha256": "7a9d12fd77da393352b27e391bd642e5dc0f364af2bed644068a21a117b6a911",
          "sha1": "2a9d352c6b888815557bc702bba20c4108893461",
          "md5": "fe2d308238344423dc1d2593fc514bfe"
        }
      ]
    }
  ]
}
