{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly.jar",
          "size": 11014913,
          "sha512": "3a9e217d1821b98f936398a507226ada7406461592af0c709aef6baca8a41019f1abb7da94a14b5f07a6030eeab4f4431fd5088509ff30117ae565e159ba3db8",
          "sha256": "8072d5853e6026774694bc8e967041bcd5d8e160a0df3e2ba10df59d112cd852",
          "sha1": "502578bc94e65f4e38117960004f82c6b13cec6c",
          "md5": "522b703e1e9967fa3678b7bfe68b2980"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly.jar",
          "size": 11014913,
          "sha512": "3a9e217d1821b98f936398a507226ada7406461592af0c709aef6baca8a41019f1abb7da94a14b5f07a6030eeab4f4431fd5088509ff30117ae565e159ba3db8",
          "sha256": "8072d5853e6026774694bc8e967041bcd5d8e160a0df3e2ba10df59d112cd852",
          "sha1": "502578bc94e65f4e38117960004f82c6b13cec6c",
          "md5": "522b703e1e9967fa3678b7bfe68b2980"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-sources.jar",
          "size": 10779315,
          "sha512": "5a814aff2d0758cf75c602fb41c50f1553af78419fddf1fb36403a1423ec5968fc2a2c432f6aeaf2ed9529b823883a2cdf89a646b05e0c4bb0574767f739d51b",
          "sha256": "e817616a3fb55071db595a75f6180d93cb8c6c4a6539c471f7709dc1f6d3019e",
          "sha1": "23b6df19778ec37218e5fa55a6c33c71f3defac3",
          "md5": "0d79972148a6744d5d744f15fe0651fe"
        }
      ]
    }
  ]
}
