{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.0.7-nightly",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly.jar",
          "size": 11230123,
          "sha512": "d23b6fc043fac026e0bc263b637bb1805c417cd25c777948677ba94475cf93a21d3e5584668e2527c0ee0cb54dd7fb2a12f1f7f9bb50b8c4842d882b14bdc430",
          "sha256": "825a2760e66ed9db9de10b8d2249159f5f847c6662d6c61cf84c0abebda2af1c",
          "sha1": "5c265f109d7e83c16e4170d5ee76316d76253a52",
          "md5": "65604c792f6c176f29bb26d23eedd4c1"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly.jar",
          "size": 11230123,
          "sha512": "d23b6fc043fac026e0bc263b637bb1805c417cd25c777948677ba94475cf93a21d3e5584668e2527c0ee0cb54dd7fb2a12f1f7f9bb50b8c4842d882b14bdc430",
          "sha256": "825a2760e66ed9db9de10b8d2249159f5f847c6662d6c61cf84c0abebda2af1c",
          "sha1": "5c265f109d7e83c16e4170d5ee76316d76253a52",
          "md5": "65604c792f6c176f29bb26d23eedd4c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.0.7-nightly-sources.jar",
          "url": "gtecore-1.20.1-3.0.7-nightly-sources.jar",
          "size": 11046396,
          "sha512": "1f269630f08df46207043f6dbd87965cd7d0b1f79bc36156df5e00ae08928e6c3ae6cbef73c539be7b60f509399c3a4891c89c3abda9786b2df74c1bd693b38e",
          "sha256": "fc43cece19c6f7939d703a5c5d78e8ac3214e5289281b49cf1c4321335fdea2c",
          "sha1": "e9b3a75f4950a5cdd28ab248adc61baa660c8ff8",
          "md5": "a65b9fa12827b67a433e34e79cb4f3f3"
        }
      ]
    }
  ]
}
