{
  "formatVersion": "1.1",
  "component": {
    "group": "org.satou.gtecore",
    "module": "gtecore-1.20.1",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.1.0.jar",
          "url": "gtecore-1.20.1-3.1.0.jar",
          "size": 11249646,
          "sha512": "9ec1df6bc4beee2b39fd2bb123cf95260753a6f92b14f531c8e3d8f95e79e97e751f38ee78f30dea2add82864fd75d799c656d2bf3ec224126d464af731204f8",
          "sha256": "e7ca991ba0a3cc5d8a68e4938ea1e4ca086a981b0732d8a9a9f055142d372f6b",
          "sha1": "f84cf4e85239f840b095487ba5e5e08861238d17",
          "md5": "06dd879ca8f91d7678a58ad569ff6a66"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.1.0.jar",
          "url": "gtecore-1.20.1-3.1.0.jar",
          "size": 11249646,
          "sha512": "9ec1df6bc4beee2b39fd2bb123cf95260753a6f92b14f531c8e3d8f95e79e97e751f38ee78f30dea2add82864fd75d799c656d2bf3ec224126d464af731204f8",
          "sha256": "e7ca991ba0a3cc5d8a68e4938ea1e4ca086a981b0732d8a9a9f055142d372f6b",
          "sha1": "f84cf4e85239f840b095487ba5e5e08861238d17",
          "md5": "06dd879ca8f91d7678a58ad569ff6a66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gtecore-1.20.1-3.1.0-sources.jar",
          "url": "gtecore-1.20.1-3.1.0-sources.jar",
          "size": 11061146,
          "sha512": "8530c7b9ca28da91179eaf0461076e31319d9d461c4c5db6f65c3a80d0ae91e95268bb262761df8263f61e5d13efb5e1075919a92141925b5a5ededeb44a5d2f",
          "sha256": "cf4c1c87d3da2d5169d57453a03ac87f7361f2373e7d3fb87f5a8e6698066479",
          "sha1": "0465539a1566039871cdf943ad8c1398e64a6454",
          "md5": "13592b1f6fa57fab8e4f7a2a371df064"
        }
      ]
    }
  ]
}
