name: "Refresh"
on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:
  
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install python deps
        run: pip install -r .github/localization/requirements.txt

      - name: Generate Translate Keys
        run: python .github/localization/ftbquest_localization.py

      - name: Generate Traditional Translate Keys
        run: python .github/localization/chinese_converter.py

      - name: Make packwiz executable
        run: chmod +x .github/packwiz

      - name: Packwiz Refresh
        run: .github/packwiz refresh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Quest Localization & Refresh
